Fix bug in 'gvim-nofork' script

diff --git a/bin/gvim-nofork b/bin/gvim-nofork
--- a/bin/gvim-nofork
+++ b/bin/gvim-nofork
@@ -3,13 +3,13 @@
 case $(type -t gvim) in
 file)
     exec gvim --nofork "$@"
-    exit "cannot execute gvim, trying vim" >&2
+    echo "cannot execute gvim, trying vim" >&2
     ;;
 esac
 case $(type -t vim) in
 file)
     exec vim "$@"
-    exit "cannot execute vim" >&2
+    echo "cannot execute vim" >&2
     exit 1
     ;;
 esac
