Port to OSX Xcode
Replace GNU ln(1) options --symbolic --force with GNU/BSD common options
-s and -f.  Remove GNU-only option -T, use rm -f on existing symlink
instead.

If ls(1) is not GNU, then set CLICOLOR env var instead of passing
command-line --color option.

If gvim(1) is unavailable, revert to vim(1) if possible.

diff --git a/bin/gvim-nofork b/bin/gvim-nofork
--- a/bin/gvim-nofork
+++ b/bin/gvim-nofork
@@ -1,2 +1,14 @@
 #!/bin/sh
-exec gvim --nofork "$@"
+
+case $(type -t gvim) in
+file)
+    exec gvim --nofork "$@"
+    ;;
+esac
+case $(type -t vim) in
+file)
+    exec vim "$@"
+    ;;
+esac
+echo "not found: gvim or vim" >&2
+exit 1
